apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: critical-subscriber
  labels:
    app: critical-subscriber
    component: rabbitmq-subscriber
spec:
  #serviceName: svc-critical-subscriber
  podManagementPolicy: Parallel # Default is OrderedReady
  replicas: 1 # Default is 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: critical-subscriber # Has to match .spec.template.metadata.labels
      component: rabbitmq-subscriber
  template:
    metadata:
      labels:
        app: critical-subscriber # Has to match .spec.selector.matchLabels
        component: rabbitmq-subscriber
    spec:
      terminationGracePeriodSeconds: 10
      #      affinity:
      #        podAntiAffinity:
      #          requiredDuringSchedulingIgnoredDuringExecution:
      #          - labelSelector:
      #              matchExpressions:
      #              - key: app
      #                operator: In
      #                values:
      #                - critical-subscriber
      #            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: critical-subscriber
          image: khteh/rabbitmq-subscriber:latest
          imagePullPolicy: Always
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production
            - name: UserName
              valueFrom:
                secretKeyRef:
                  name: guest-secret
                  key: username
            - name: Password
              valueFrom:
                secretKeyRef:
                  name: guest-secret
                  key: password
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
            #          hostPort: 8081
            - containerPort: 443
              name: https
              protocol: TCP
          #          hostPort: 8082
          volumeMounts:
            - name: appsettings-criticalsubscriber-production
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
              readOnly: true
            - name: log
              mountPath: /var/log/subscriber
          #resources:
          #  limits:
          #    cpu: 500m
          #    memory: 2Gi
        - name: fluentd
          image: khteh/fluentd:latest
          volumeMounts:
            - name: log
              mountPath: /var/log/subscriber
            - name: subscriber-fluentd-config
              mountPath: /fluentd/etc
            - name: elasticsearch-template
              mountPath: /tmp/elasticsearch_template.json
              subPath: elasticsearch_template.json
              readOnly: true
            #- mountPath: /fluentd/elastic/tls.crt
            #  name: elasticsearch-ca
            #  subPath: tls.crt
            #  readOnly: true
          #resources:
          #  limits:
          #    cpu: 500m
          #    memory: 2Gi
      volumes:
        - name: appsettings-criticalsubscriber-production
          configMap:
            name: appsettings-criticalsubscriber-production
        - name: subscriber-fluentd-config
          configMap:
            name: subscriber-fluentd-config
        - name: elasticsearch-template
          configMap:
            name: elasticsearch-template
        - name: log
          emptyDir: {}
