apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  labels:
    app: neo4j
    component: graph-db
data:
  neo4j.conf: |
    # Bolt keep alive
    # this helps to ensure that LoadBalancers do not close bolt connections that are in use but appear idle
    server.bolt.enabled = true
    server.http.enabled = true
    server.https.enabled = false
    server.bolt.connection_keep_alive = 30
    server.bolt.connection_keep_alive_for_requests = ALL
    server.bolt.connection_keep_alive_streaming_scheduling_interval = 30
    # Other
    internal.dbms.ssl.system.ignore_dot_files = true
    # Import - Only works by copying the files to be imported into the pod in this folder, then run the import externally using GraphDatabase.driver
    server.directories.import = import
    # Metrics
    #server.directories.metrics = /metrics
    #server.bolt.tls_level: REQUIRED
    server.default_listen_address = 0.0.0.0
    # Paths of directories in the installation.
    server.directories.data = /data
    #server.directories.plugins = plugins
    server.directories.logs = /var/log/neo4j
    server.directories.lib = lib
    server.directories.run = run
    #server.directories.licenses=licenses
    server.directories.transaction.logs.root = /var/log/neo4j/transactions
    server.databases.default_to_read_only = false
    # Use more reliable defaults SSL / TLS settings for K8s
    dbms.ssl.policy.bolt.client_auth = NONE
    dbms.ssl.policy.https.client_auth = NONE
    dbms.security.allow_csv_import_from_file_urls = true
    dbms.security.procedures.unrestricted = gds.*,algo.*,apoc.*,apoc.trigger.*,apoc.meta.*,apoc.meta.data.*
    dbms.security.procedures.allowlist = gds.*,algo.*,apoc.*,apoc.trigger.*,apoc.meta.*,apoc.meta.data.*
    dbms.security.http_auth_allowlist = gds.*,algo.*,apoc.*,apoc.trigger.*,apoc.meta.*,apoc.meta.data.*
