apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j
  labels:
    app: db-neo4j
    component: neo4j
spec:
  serviceName: svc-neo4j
  podManagementPolicy: Parallel # Default is OrderedReady
  replicas: 1 # Default is 1
  selector:
    matchLabels:
      app: db-neo4j # Has to match .spec.template.metadata.labels
      component: neo4j
  template:
    metadata:
      labels:
        app: db-neo4j # Has to match .spec.selector.matchLabels
        component: neo4j
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: neo4j
          image: khteh/neo4j:latest
          imagePullPolicy: Always
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: NEO4J_AUTH
          ports:
            - name: https
              containerPort: 7473
            - name: http
              containerPort: 7474
            - name: bolt
              containerPort: 7687
          livenessProbe:
            tcpSocket:
              port: 7687
            failureThreshold: 5
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 7687
            failureThreshold: 10
            timeoutSeconds: 10
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
          # https://neo4j.com/docs/operations-manual/current/kubernetes/persistent-volumes/
          volumeMounts:
            - name: neo4j-conf
              mountPath: /config/neo4j.conf
            #- name: healthcare-neo4j
            #  mountPath: /import/neo4j.dump
            #  subPath: neo4j.dump
            #  readOnly: false
            - name: neo4j-persistent-storage
              mountPath: /data
              readOnly: false
            - name: log
              mountPath: /var/log/neo4j
      volumes:
        - name: neo4j-conf
          projected:
            defaultMode: 0440
            sources:
              - configMap:
                  name: neo4j-config
        #- name: healthcare-neo4j
        #  configMap:
        #    name: healthcare-neo4j
        - name: log
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: neo4j-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
