apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: elasticsearch-secret
  namespace: default
stringData:
  username: Z3Vlc3Q=
  password: UEAkJHcwcmQ=
  roles: kibana_admin,superuser,snapshot_user
