apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pgadmin-secret
  namespace: default
data:
  pgadmin-email: bWVAZW1haWwuY29t
  pgadmin-password: UEAkJHcwcmQ=
  servers.json: ewoJIlNlcnZlcnMiOiB7CiAgICAiMSI6IHsKICAgICAgIk5hbWUiOiAicGdhZG1pbi1rOHMiLAogICAgICAiSG9zdCI6ICJzdmMtcG9zdGdyZXNxbCIsCiAgICAgICJVc2VybmFtZSI6ICJndWVzdCIsCiAgICAgICJQYXNzd29yZCI6ICJQQCQkdzByZCIsCiAgICAgICJHcm91cCI6ICJwZ2FkbWluLWs4cyIsCiAgICAgICJQb3J0IjogNTQzMiwKICAgICAgIlNTTE1vZGUiOiAicHJlZmVyIiwKICAgICAgIk1haW50ZW5hbmNlREIiOiAicG9zdGdyZXMiLAogICAgICAiSW5jbHVkZSBFcnJvciBEZXRhaWwiOiB0cnVlCiAgICB9CiAgfQp9
