apiVersion: v1
kind: Service 
metadata:
  name: svc-postgresql
  labels: 
    app: postgresql
    component: sql-db
spec:
  selector:
    app: postgresql
    component: sql-db
#    tier: database
  ports:
  - name: postgresql
    port: 5432
    targetPort: postgresql
  clusterIP: None # Headless
  selector:
    app: postgresql
    component: sql-db
---
apiVersion: v1
kind: Service 
metadata:
  name: svc-postgresql-nodeport
  labels: 
    app: postgresql
    component: sql-db
spec:
  selector:
    app: postgresql
    component: sql-db
#    tier: database
  ports:
  - name: postgresql
    port: 5432
    nodePort: 30000
  type: NodePort
