apiVersion: v1
kind: ConfigMap
metadata:
  name: access-log-template
  namespace: default
data:
  access_log_template.json: |
    {
      "index_patterns": ["aspnetcorewebapi.logs-*", "pythonrestapi.logs-*", "ragagent.logs-*", "hypoercorn.logs-*", "nodejsrestapi.logs-*", "ollama.logs-*"],
      "version": 3,
      "settings": {
        "number_of_shards": 3
      },
      "mappings": {
          "_source": {
            "enabled": true
          },          
          "properties": {
              "location_properties": { "type": "geo_point" },
              "location_string": { "type": "geo_point" },
              "location_array": { "type": "geo_point" }
          }
      }
    }
