apiVersion: v1
kind: ConfigMap
metadata:
  name: access-log-template
  namespace: default
data:
  access_log_template.json: |
    {
      "index_patterns": ["aspnetcorewebapi.logs*", "biz4x-backend.logs-*", "biz4x-frontend.logs-*", "identityservice.logs-*"],
      "settings": {
        "number_of_shards": 5
      },
      "mappings": {
          "properties": {
            "type": { "type": "keyword" },
            "location_array": { "type": "geo_point" },
            "location_properties": { "type": "geo_point" },
            "location_string": { "type": "geo_point" }
          }
      }
    }
