apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: kyberlife
  labels:
    app: apmserver
    component: eck
spec:
  version: 8.9.1
  count: 3
  secureSettings:
    - secretName: kyberlife-es-elastic-user
  config:
    output:
      elasticsearch:
        hosts: ["https://kyberlife-es-internal-http.default:9200"]
        username: elastic
        password: "${elastic}"
        protocol: "https"
        ssl.certificate_authorities:
          ["/usr/share/apm-server/config/elasticsearch-ca/tls.crt"]
  podTemplate:
    spec:
      containers:
        - name: apm-server
          volumeMounts:
            - mountPath: /usr/share/apm-server/config/elasticsearch-ca
              name: elasticsearch-ca
              readOnly: true
            - name: elastic-stack-tls-certs
              mountPath: /usr/share/apm-server/config/localhost.crt
              subPath: localhost.crt
              readOnly: true
            - name: elastic-stack-tls-certs
              mountPath: /usr/share/apm-server/config/localhost.key
              subPath: localhost.key
              readOnly: true
      volumes:
        - name: elasticsearch-ca
          secret:
            defaultMode: 420
            optional: false
            secretName: elasticsearch-eck-ca # This is the secret that holds the Elasticsearch CA cert
        - name: elastic-stack-tls-certs
          secret:
            secretName: elastic-stack-tls-certs
            items:
              - key: localhost.crt
                path: localhost.crt
              - key: localhost.key
                path: localhost.key
