apiVersion: v1
kind: ConfigMap
metadata:
  name: appsettings-production
  namespace: default
data:
  appsettings.Production.json: |
    {
      "Kestrel": {
          "EndpointDefaults": {
            "Protocols": "Http2"
          },
          "Endpoints": {
             "Https": {
                "Url": "https://*",
                "Protocols": "Http2",
                "Certificate": {
                    "Path": "/tmp/localhost.pfx",
                    "Password": "AspNetCoreWebApi"
                }
              }
          },
          "Certificates": {
              "Default": {
                "Path": "/tmp/localhost.pfx",
                "Password": "AspNetCoreWebApi"
              }
          }
       },
       "DetailedErrors": true,
       "Logging": {
           "LogLevel": {
              "Default": "Debug",
              "Grpc": "Warning",
              "System": "Warning",
              "Microsoft.AspNetCore": "Warning",
              "Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker": "Error",
              "Microsoft.AspNetCore.Components.Server": "Debug",
              "Microsoft.AspNetCore.Components": "Debug"
            },
            "Debug": {
                "LogLevel": {
                    "Default": "Debug"
                }
            },
            "Console": {
                "IncludeScopes": true,
                "LogLevel": {
                    "Microsoft.AspNetCore.Mvc.Razor.Internal": "Warning",
                    "Microsoft.AspNetCore.Mvc.Razor.Razor": "Debug",
                    "Microsoft.AspNetCore.Mvc.Razor": "Error",
                    "Default": "Debug"
                }
            },
            "EventSource": {
                "LogLevel": {
                    "Microsoft": "Debug"
                }
            },
            "EventLog": {
                "LogLevel": {
                    "Microsoft": "Debug"
                }
            }
         },
        "Serilog": {
            "Using": [ "Serilog.Sinks.File" ],
            "MinimumLevel": {
                "Default": "Debug",
                "Override": {
                    "Microsoft": "Debug",
                    "System": "Warning",
                    "Microsoft.Hosting.Lifetime": "Information",
                    "Microsoft.EntityFrameworkCore.Database.Command": "Warning"
                }
            },
            "Enrich": [ "FromLogContext", "WithMachineName", "WithThreadId" ],
            "WriteTo": [
                {
                    "Name": "File",
                    "Args": {
                        "Args": {
                            "outputTemplate": "{Timestamp} {Level} {EventId} {Message:j} {Properties}{NewLine}{Exception}{NewLine}"
                        },
                        "Enrich": [ "FromLogContext" ],
                        "path": "/var/log/aspnetcore/log",
                        "rollingInterval": "Day",
                        "retainedFileCountLimit": 3,
                        "formatter": "Serilog.Formatting.Elasticsearch.ElasticsearchJsonFormatter, Serilog.Formatting.Elasticsearch, Version=0.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10"
                    }
                }
            ]
        }
      }
