apiVersion: v1
kind: Secret
type: Opaque
data:
  aspnetcorewebapi.postgresql.json: ewogICAgIkNvbm5lY3Rpb25TdHJpbmdzIjogewogICAgICAgICJEZWZhdWx0IjogIkhvc3Q9c3ZjLXBvc3RncmVzcWw7RGF0YWJhc2U9QXNwTmV0Q29yZVdlYkFwaTtVc2VybmFtZT1ndWVzdDtQYXNzd29yZD1QQCQkdzByZCIKICAgIH0KfQo=
