apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    component: elasticsearch
    app: elasticsearch
    role: data
spec:
  serviceName: svc-elasticsearch
  replicas: 2 # Default is 1
  selector:
    matchLabels:
      app: app-elasticsearch # Has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        component: elasticsearch
        app: app-elasticsearch
        role: data
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 2000
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - data
              topologyKey: "kubernetes.io/hostname"
      #initContainers:
      #  - name: fix-volume-mount-permission
      #    image: busybox
      #    command: ["sh", "-c", "chown -R 1000:0 /usr/share/elasticsearch/data"]
      #    volumeMounts:
      #      - name: elasticsearch-pvc
      #        mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          image: khteh/elasticsearch:latest
          imagePullPolicy: Always
          env:
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: elasticsearch-config
                  key: ES_JAVA_OPTS
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NODE_MASTER
              value: "false"
            - name: NODE_INGEST
              value: "false"
            - name: HTTP_ENABLE
              value: "true"
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
          resources:
            requests:
              cpu: 0.25
            limits:
              cpu: 1
          #        livenessProbe:
          #          tcpSocket:
          #            port: transport
          #          initialDelaySeconds: 60
          #          periodSeconds: 10
          #          timeoutSeconds: 1
          #          successThreshold: 1
          #          failureThreshold: 3
          #        readinessProbe:
          #          httpGet:
          #            path: /_cluster/health
          #            port: http
          #          initialDelaySeconds: 60
          #          periodSeconds: 10
          #          timeoutSeconds: 5
          #          successThreshold: 1
          #          failureThreshold: 3
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9300
              name: transport
          volumeMounts:
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: elasticsearch-persistent-storage
              mountPath: /usr/share/elasticsearch/data
            - name: server-key
              mountPath: /usr/share/elasticsearch/config/server.key
              subPath: server.key
              readOnly: true
            - name: server-cert
              mountPath: /usr/share/elasticsearch/config/server.cert
              subPath: server.cert
              readOnly: true
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
            items:
              - key: elasticsearch-data.yml
                path: elasticsearch.yml
        - name: server-cert
          secret:
            secretName: server-cert
            items:
              - key: server.cert
                path: server.cert
        - name: server-key
          secret:
            secretName: server-key
            items:
              - key: server.key
                path: server.key
  volumeClaimTemplates:
    - metadata:
        name: elasticsearch-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
