apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: default
data:
  elasticsearch-master.yml: |+
    cluster.name: elasticsearch
    cluster.initial_master_nodes: 
      - elasticsearch-master-0
      - elasticsearch-master-1
      - elasticsearch-master-2
    discovery.seed_hosts:
      - elasticsearch-master-0.svc-elasticsearch-discovery.default.svc.cluster.local:9300
      - elasticsearch-master-1.svc-elasticsearch-discovery.default.svc.cluster.local:9300
      - elasticsearch-master-2.svc-elasticsearch-discovery.default.svc.cluster.local:9300
    script.painless.regex.enabled: true
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    network.host: _site_
    node.name: ${HOSTNAME}
    node.roles: ["master"]
    bootstrap.memory_lock: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/server.key
    xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/server.cert

  elasticsearch-data.yml: |+
    cluster.name: elasticsearch
    cluster.initial_master_nodes: 
      - elasticsearch-master-0
      - elasticsearch-master-1
      - elasticsearch-master-2
    discovery.seed_hosts:
      - elasticsearch-master-0.svc-elasticsearch-discovery.default.svc.cluster.local:9300
      - elasticsearch-master-1.svc-elasticsearch-discovery.default.svc.cluster.local:9300
      - elasticsearch-master-2.svc-elasticsearch-discovery.default.svc.cluster.local:9300
    script.painless.regex.enabled: true
    http.cors.enabled: true
    http.cors.allow-origin: "*"
    network.host: _site_
    node.name: ${HOSTNAME}
    node.roles: ["data"]
    bootstrap.memory_lock: true
    xpack.security.transport.ssl.enabled: true
    xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/server.key
    xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/server.cert

  ES_JAVA_OPTS: -Xms5g -Xmx5g -Djna.tmpdir=/tmp -Djava.lang.RuntimePermission=modifyThread --enable-preview
