apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: elasticsearch-secret
  namespace: default
stringData:
  username: <username>
  password: <password>
  roles: kibana_admin,superuser,snapshot_user
