apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-master
  labels:
    component: elasticsearch
    app: elasticsearch-master
    role: master
spec:
  serviceName: svc-elasticsearch-discovery
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch-master # Has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        component: elasticsearch
        app: elasticsearch-master # Has to match .spec.selector.matchLabels
        role: master
    spec:
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 2000
      #      affinity:
      #        podAntiAffinity:
      #          requiredDuringSchedulingIgnoredDuringExecution:
      #            - labelSelector:
      #                matchExpressions:
      #                  - key: role
      #                    operator: In
      #                    values:
      #                      - master
      #              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: elasticsearch
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          image: khteh/elasticsearch:latest
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/sh", "-c", "ulimit -l unlimited"]
          env:
            - name: ES_JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  name: elasticsearch-config
                  key: ES_JAVA_OPTS
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: NUMBER_OF_MASTERS
              value: "3"
            - name: NODE_MASTER
              value: "true"
            - name: NODE_INGEST
              value: "false"
            - name: NODE_DATA
              value: "false"
            - name: HTTP_ENABLE
              value: "false"
            - name: PROCESSORS
              valueFrom:
                resourceFieldRef:
                  resource: limits.cpu
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: password
          resources:
            requests:
              cpu: 0.25
            limits:
              cpu: 1
          ports:
            - containerPort: 9300
              name: transport
          livenessProbe:
            tcpSocket:
              port: transport
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: elasticsearch-config
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
            - name: es-master-persistent-storage
              mountPath: /usr/share/elasticsearch/data
            - name: server-key
              mountPath: /usr/share/elasticsearch/config/server.key
              subPath: server.key
              readOnly: true
            - name: server-cert
              mountPath: /usr/share/elasticsearch/config/server.cert
              subPath: server.cert
              readOnly: true
      volumes:
        - name: elasticsearch-config
          configMap:
            name: elasticsearch-config
            items:
              - key: elasticsearch-master.yml
                path: elasticsearch.yml
        - name: server-cert
          secret:
            secretName: server-cert
            items:
              - key: server.cert
                path: server.cert
        - name: server-key
          secret:
            secretName: server-key
            items:
              - key: server.key
                path: server.key
  volumeClaimTemplates:
    - metadata:
        name: es-master-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
