apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-elastic-agent
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - pods
      - nodes
      - namespaces
    verbs:
      - get
      - watch
      - list
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs:
      - get
      - create
      - update
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-elastic-agent
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-elastic-agent
subjects:
  - kind: ServiceAccount
    name: sa-elastic-agent
    namespace: default
roleRef:
  kind: ClusterRole
  name: role-elastic-agent
  apiGroup: rbac.authorization.k8s.io
