kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-elasticsearch
  labels:
    app: elasticsearch
    component: elasticsearch
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-elasticsearch-master
  labels:
    app: elasticsearch-master
    component: elasticsearch
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
