apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: elasticsearch-secret
  namespace: default
stringData:
  username: kyberlife
  password: P@$$w0rd
  roles: kibana_admin,superuser,snapshot_user
