apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: gcloud-secret
data:
  application_default_credentials.json: |
    k create secret generic gcloud-secret --from-file=~/.config/gcloud/application_default_credentials.json
