apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gorestapi
  labels:
    app: gorestapi
    component: gorestapi
spec:
  serviceName: svc-gorestapi
  podManagementPolicy: Parallel # Default is OrderedReady
  replicas: 2 # Default is 1
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: gorestapi # Has to match .spec.template.metadata.labels
      component: gorestapi
  template:
    metadata:
      labels:
        app: gorestapi # Has to match .spec.selector.matchLabels
        component: gorestapi
    spec:
      terminationGracePeriodSeconds: 10
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - gorestapi
#            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: gorestapi
        image: khteh/gorestapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: https
          protocol: TCP
#          hostPort: 8082
        readinessProbe:
          httpGet:
            path: /ready
            port: https
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        livenessProbe:
          httpGet:
            path: /live
            port: https
            scheme: HTTPS
          initialDelaySeconds: 20
          periodSeconds: 3
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
      - name: fluentd
        image: khteh/fluentd:latest
        env:
        - name: FLUENTD_ARGS
          value: -c /etc/td-agent/td-agent.conf
        volumeMounts:
        - name: log
          mountPath: /var/log/aspnetcore
        - name: fluentd-config
          mountPath: /etc/td-agent
        - name: access-log-template
          mountPath: /tmp/access_log_template.json
          subPath: access_log_template.json
          readOnly: true
        resources:
          limits:
            cpu: 500m
            memory: 2Gi
      volumes:
      - name: mysql-connection
        secret:
          secretName: gorestapi
          items:
          - key: gorestapi.mysql.json
            path: appsettings.mysql.json
      - name: fluentd-config
        configMap:
          name: fluentd-config
      - name: access-log-template
        configMap:
          name: access-log-template
      - name: log
        emptyDir: {}
