apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: aspnetcorewebapi-hpa
  namespace: default
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: aspnetcorewebapi
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: aspnetcorewebapi
      target: 
        type: Utilization
        averageUtilization: 75
  - type: Object
    object: 
      metric: 
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress 
        name: ingress
      target: 
        type: Value
        value: 10k
#  - type: ContainerResource
#    containerResource:
#      name: memory
#      container: aspnetcorewebapi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: restapi-hpa
  namespace: default
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: restapi
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: restapi
      target: 
        type: Utilization
        averageUtilization: 75
  - type: Object
    object: 
      metric: 
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress 
        name: ingress
      target: 
        type: Value
        value: 10k
#  - type: ContainerResource
#    containerResource:
#      name: memory
#      container: restapi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pythonrestapi-hpa
  namespace: default
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: pythonrestapi
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: pythonrestapi
      target: 
        type: Utilization
        averageUtilization: 75
  - type: Object
    object: 
      metric: 
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress 
        name: ingress
      target: 
        type: Value
        value: 10k
#  - type: ContainerResource
#    containerResource:
#      name: memory
#      container: pythonrestapi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejsrestapi-hpa
  namespace: default
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: nodejsrestapi
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: nodejsrestapi
      target: 
        type: Utilization
        averageUtilization: 75
  - type: Object
    object: 
      metric: 
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress 
        name: ingress
      target: 
        type: Value
        value: 10k
#  - type: ContainerResource
#    containerResource:
#      name: memory
#      container: nodejsrestapi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kibana-hpa
  namespace: default 
spec:
  minReplicas: 2
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: StatefulSet
    name: kibana
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: kibana
      target: 
        type: Utilization
        averageUtilization: 75
  - type: Object
    object: 
      metric: 
        name: requests-per-second
      describedObject:
        apiVersion: networking.k8s.io/v1
        kind: Ingress 
        name: ingress
      target: 
        type: Value
        value: 10k
#  - type: ContainerResource
#    containerResource:
#      name: memory
#      container: kibana
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rabbitmq-hpa
  namespace: default 
spec:
  minReplicas: 3
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1 
    kind: StatefulSet
    name: rabbitmq
  metrics:
  - type: ContainerResource
    containerResource:
      name: cpu
      container: rabbitmq-k8s
      target: 
        type: Utilization
        averageUtilization: 75
