apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
#    nginx.ingress.kubernetes.io/app-root: /
#    nginx.ingress.kubernetes.io/affinity: "cookie"
#    nginx.ingress.kubernetes.io/session-cookie-name: "ingress-cookie"
#    nginx.ingress.kubernetes.io/session-cookie-name: "route"
#    nginx.ingress.kubernetes.io/session-cookie-hash: "sha1"
#    nginx.ingress.kubernetes.io/session-cookie-expires: "600"
#    nginx.ingress.kubernetes.io/session-cookie-max-age: "600"
#    certmanager.k8s.io/issuer: "iconverse-letsencrypt"
#    certmanager.k8s.io/acme-challenge-type: http01
#    kubernetes.io/tls-acme: 'true'
  labels:
    app: ingress
spec:
#  tls:
#  - hosts:
#    - iconverse-k8s.taiger.io
#    secretName: iconverse-k8s.tls
  rules:  
  - host:
    http: 
      paths:
      - pathType: Prefix
        path: /apistarter(/|$)(.*)
        backend:
          service:
            name: svc-aspnetapistarter
            port:
              number: 5000
      - pathType: Prefix
        path: //apistarter(/|$)(.*)
        backend:
          service:
            name: svc-aspnetapistarter
            port:
              number: 5000
#     - pathType: Prefix
#       path: /(/|$)(.*)
#       backend:
#          service:
#            name: svc-biz4xfrontend
#            port:
#               number: 5001
#     - pathType: Prefix
#       path: //(//|$)(.*)
#       backend:
#          service:
#            name: svc-biz4xfrontend
#            port:
#               number: 5001
      - pathType: Prefix
        path: /biz4x(/|$)(.*)
        backend:
          service:
            name: svc-biz4xfrontend
            port:
              number: 5001
      - pathType: Prefix
        path: //biz4x(/|$)(.*)
        backend:
          service:
            name: svc-biz4xfrontend
            port:
              number: 5001
      - pathType: Prefix
        path: /kibana(/|$)(.*)
        backend:
          service:
            name: svc-kibana
            port:
              number: 5601
      - pathType: Prefix
        path: //kibana(/|$)(.*)
        backend:
          service:
            name: svc-kibana
            port:
              number: 5601
