apiVersion: v1
kind: Service 
metadata:
  name: svc-mysql-slave
  labels: 
    app: mysql-slave
    component: mysql
spec:
  selector:
    app: mysql-slave
    component: mysql
#    tier: database
  ports:  
  - port: 3306
    name: mysql
  clusterIP: None # Headless
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-slave
  labels:
    app: mysql-slave
    component: mysql
spec:
  serviceName: svc-mysql-slave
  podManagementPolicy: Parallel # Default is OrderedReady
  replicas: 1 # Default is 1
  selector:
    matchLabels:
      app: mysql-slave # Has to match .spec.template.metadata.labels
      component: mysql
  template:
    metadata:
      labels:
        app: mysql-slave # Has to match .spec.selector.matchLabels
        component: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
#        image: mysql:latest
        image: khteh/mysql-slave:latest
        imagePullPolicy: Always
#        command: ["mysqld"]
#        args: ["--lower_case_table_names=1", "--skip-ssl", "--ignore-db-dir=lost+found"]
        lifecycle:
          postStart:
            exec:
              command: ["/usr/local/bin/postinit.sh"]
        env:
#         - name: MYSQL_ALLOW_EMPTY_PASSWORD
#           value: "1"
         - name: MYSQL_ROOT_HOST
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: mysql-root-host
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: mysql-root-password
         - name: MYSQL_REPLICATION_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: mysql-replication-password
         - name: MYSQL_REPLICATION_USER
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: mysql-replication-user
         - name: MYSQL_USER
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: mysql-user
         - name: MYSQL_PASSWORD
           valueFrom:
             secretKeyRef:
               name: mysql-secret
               key: mysql-password
         - name: MYSQL_MASTER_SERVICE_HOST
           value: svc-mysql-master
         - name: MYSQL_DATABASE
           value: biz4xdb
         - name: MYSQL_DATABASE_1
           value: AspNetCoreApiStarter
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-slave-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql
#        - name: mysql-initdb
#          mountPath: /docker-entrypoint-initdb.d
      volumes:
#      - name: mysql-initdb
#        configMap:
#          name: mysqlinit
  volumeClaimTemplates:
  - metadata:
      name: mysql-slave-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: local-storage
      resources:
        requests:
          storage: 2Gi
