apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.config: |
    user nginx;
    worker_processes  auto;
    # set open fd limit to 30000
    #worker_rlimit_nofile 10000;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
      worker_connections  10240;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main
              'remote_addr:$remote_addr\t'
              'time_local:$time_local\t'
              'method:$request_method\t'
              'uri:$request_uri\t'
              'host:$host\t'
              'status:$status\t'
              'bytes_sent:$body_bytes_sent\t'
              'referer:$http_referer\t'
              'useragent:$http_user_agent\t'
              'forwardedfor:$http_x_forwarded_for\t'
              'request_time:$request_time';
      access_log /var/log/nginx/access.log main;
      rewrite_log on;
      sendfile        on;
      #tcp_nopush     on;     
      keepalive_timeout  65;
      #gzip  on;
      #include /etc/nginx/conf.d/*.conf; This must be commented out!
      #upstream svc-aspnetcorewebapi {
      #  server svc-aspnetcorewebapi:5000;
      #  keepalive 1024;
      #}
      server {
        listen 80;
        access_log /var/log/nginx/app.access_log main;
        error_log /var/log/nginx/app.error_log;
        #set $restapi http://svc-web.default.svc.cluster.local:8080;
        set $apistarter http://svc-aspnetcorewebapi.default.svc.cluster.local:5000/;
        resolver kube-dns.kube-system valid=10s;
        location /apistarter/ {
          #proxy_pass http://svc-web;
          proxy_pass $apistarter;
          proxy_http_version 1.1;
        }
      }
    }
