kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-log-volume
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
#  storageClassName: managed-premium # Use this for AKS
  hostPath:
    path: "/mnt/nginx/log"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-log-volume-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
