kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-pgadmin
  labels:
    app: pgadmin
    component: postgresql
spec:
  storageClassName: efs-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
