apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    app: db-postgresql
    component: postgresql
spec:
  serviceName: svc-postgresql
  podManagementPolicy: Parallel # Default is OrderedReady
  replicas: 1 # Default is 1
  selector:
    matchLabels:
      app: db-postgresql # Has to match .spec.template.metadata.labels
      component: postgresql
  template:
    metadata:
      labels:
        app: db-postgresql # Has to match .spec.selector.matchLabels
        component: postgresql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgresql
#        image: postgresql:latest
        image: khteh/postgresql:latest
        imagePullPolicy: Always
#        command: ["postgresqld"]
#        args: ["--lower_case_table_names=1", "--skip-ssl", "--ignore-db-dir=lost+found"]
        env:
#         - name: MYSQL_ALLOW_EMPTY_PASSWORD
#           value: "1"
         - name: PGPASSWORD
           valueFrom:
             secretKeyRef:
               name: postgresql-secret
               key: postgresql-password
#         - name: POSTGRES_USER
#           valueFrom:
#             secretKeyRef:
#               name: postgresql-secret
#               key: superUser
         - name: POSTGRES_PASSWORD
           valueFrom:
             secretKeyRef:
               name: postgresql-secret
               key: superUserPassword
         - name: POSTGRES_DB
           value: AspNetCoreWebApi
         - name: POSTGRES_DB_1
           value: library
         - name: POSTGRES_DB_2
           value: school
        ports:
        - containerPort: 3306
          name: postgresql
        volumeMounts:
        - name: postgresql-persistent-storage
          mountPath: /var/lib/postgresql
          subPath: postgresql
        - name: postgresql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: postgresql-initdb
        configMap:
          name: postgresql-initdb
  volumeClaimTemplates:
  - metadata:
      name: postgresql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: local-storage
      resources:
        requests:
          storage: 10Gi
