apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  labels:
    component: postgresql
    app: db-postgresql
spec:
  serviceName: svc-postgresql
  podManagementPolicy: Parallel
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: postgresql
      app: db-postgresql
  template:
    metadata:
      labels:
        component: postgresql
        app: db-postgresql
    spec:
      terminationGracePeriodSeconds: 10
      imagePullSecrets:
      - name: imagepullsecret
      containers:
      - name: postgresql
        image: postgres:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
          name: postgresql
          protocol: TCP
        env:
        - name: PGHOST
          value: /tmp
        - name: POSTGRES_MODE
          value: primary
        - name: POSTGRES_PRIMARY_PORT
          value: "5432"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresql-secret
              key: postgresql-password
        - name: PGDATA
          value: /pgdata
        volumeMounts:
        - mountPath: "/pgdata"
          name: pgdata
          readOnly: false
        - mountPath: "/backup"
          name: backup
          readOnly: true
#        - name: postgresql-initdb
#          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: pgdata
        emptyDir: {}
      - name: backup
        emptyDir: {}
      - name: postgresql-initdb
        configMap:
          name: postgresql-initdb
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:   
      accessModes: [ "ReadWriteOnce" ]
#      storageClassName: local-storage
      resources:
        requests:
          storage: 10Gi
