kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: rabbitmq-secret
  namespace: default
stringData:
  default_user.conf: |
    default_user = user123
    default_pass = password123
  password: password123
  username: user123
