apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: rabbitmq-secret
  namespace: default
data:
  rabbitmq-secret.json: ewogICAgIlJhYmJpdE1RQ29uZmlnIjogewogICAgICAgICJDb25uZWN0aW9uTmFtZSI6ICJSYWJiaXRNUVB1YlN1YiIsCiAgICAgICAgIkVuZHBvaW50IjogInN2Yy1yYWJiaXRtcSIsCiAgICAgICAgIlVzZXJOYW1lIjogImJpejR4IiwKICAgICAgICAiUGFzc3dvcmQiOiAiYml6NHguY29tIiwKICAgICAgICAiVkhvc3QiOiAiYml6NHgiCiAgICB9Cn0K
