---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-rabbitmq 
  namespace: default 
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: svc-rabbitmq
  namespace: default 
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: svc-rabbitmq
  namespace: default
subjects:
- kind: ServiceAccount
  name: svc-rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: svc-rabbitmq
