---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-rabbitmq
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: role-rabbitmq
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-rabbitmq
  namespace: default
subjects:
  - kind: ServiceAccount
    name: sa-rabbitmq
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rolec-rabbitmq
