apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
    component: rabbitmq
spec:
  serviceName: svc-rabbitmq
  podManagementPolicy: "OrderedReady" # Default is OrderedReady. The pods need to start ONE AT A TIME! Do NOT use Parallel!
  replicas: 3
  updateStrategy: 
    type: RollingUpdate
  selector:
    matchLabels:
      app: rabbitmq
      component: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
        component: rabbitmq
    spec:
      serviceAccountName: svc-rabbitmq
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rabbitmq
            topologyKey: "kubernetes.io/hostname"
      containers:        
      - name: rabbitmq-k8s
        image: rabbitmq:latest
        volumeMounts:
        - name: rabbitmq-config
          mountPath: /etc/rabbitmq
        - name: rabbitmq-persistent-storage
          mountPath: /var/lib/rabbitmq/mnesia
        - name: rabbitmq-definitions
          mountPath: /tmp/rabbitmq.definitions.json
          subPath: rabbitmq.definitions.json
          readOnly: true
        ports:
          - name: http
            protocol: TCP
            containerPort: 15672
          - name: amqp
            protocol: TCP
            containerPort: 5672
        livenessProbe:
          # See https://www.rabbitmq.com/monitoring.html for monitoring frequency recommendations.
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          exec:
            command: ["rabbitmqctl", "status"]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        imagePullPolicy: Always
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          - name: RABBITMQ_USE_LONGNAME
            value: "true"
          # See a note on cluster_formation.k8s.address_type in the config file section
          - name: RABBITMQ_NODENAME
            value: rabbit@$(MY_POD_NAME).$(MY_POD_SERVICE_ACCOUNT).$(MY_POD_NAMESPACE).svc.cluster.local
          - name: K8S_HOSTNAME_SUFFIX
            value: .$(MY_POD_SERVICE_ACCOUNT).$(MY_POD_NAMESPACE).svc.cluster.local
          - name: K8S_SERVICE_NAME
            value: $(MY_POD_SERVICE_ACCOUNT)
          - name: RABBITMQ_ERLANG_COOKIE
            value: "mycookie" 
        resources:
          requests:
            cpu: 250m
      volumes:
        - name: rabbitmq-config
          configMap:
            name: rabbitmq-config
            items:
            - key: rabbitmq.conf
              path: rabbitmq.conf
            - key: enabled_plugins
              path: enabled_plugins
        - name: rabbitmq-definitions
          configMap:
            name: rabbitmq-definitions
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-persistent-storage
    spec:   
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
