apiVersion: v1
kind: ConfigMap
metadata:
  name: ragagent
data:
  ragagent_config.json: |
    {
        "ENVIRONMENT": "development",
        "DEBUG": true,
        "TESTING": true,
        "SECRET_KEY": "RAGAgent",
        "JWT_SECRET_KEY": "RAGAgent",
        "SQLALCHEMY_TRACK_MODIFICATIONS": false,
        "DB_MAX_CONNECTIONS": 10,
        "HEALTHZ": {
                    "live": "src.app.liveness",
                    "ready": "src.app.readiness"
                }
    }
