apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myrole
  namespace: default
rules:
  - apiGroups:
      - rbac.authorization.k8s.io
    resourceNames:
      - pod-security-policy
      - secrets
    resources:
      - podsecuritypolicies
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - patch
      - delete
