apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: default
roleRef:
  apiGroup: ""
  kind: Role
  name: myrole
subjects:
  - kind: ServiceAccount
    namespace: default
    name: default
