---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-apache-spark
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crb-apache-spark
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: sa-apache-spark
    namespace: default
