apiVersion: v1
kind: Service
metadata:
  name: svc-ragagent
  #  annotations:
  #    alb.ingress.kubernetes.io/healthcheck-path: /ragagent/actuator/health
  labels:
    component: llm-rag
    app: ragagent
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
    - name: https-tcp
      protocol: TCP
      port: 4433
      targetPort: https-tcp
    - name: https-udp
      protocol: UDP
      port: 443
      targetPort: https-udp
  clusterIP: None # Headless. type cannot be LoadBalancer
  selector:
    app: ragagent
    component: llm-rag
#    tier: frontend
#  type: LoadBalancer # Exposes web to traffic from outside of the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ragagent-nodeport
  labels:
    component: llm-rag
    app: ragagent
spec:
  ports:
    - name: https-tcp
      protocol: TCP
      port: 443
      targetPort: https-tcp
      nodePort: 31003
    - name: https-udp
      protocol: UDP
      port: 443
      targetPort: https-udp
      nodePort: 31004
  type: NodePort
  selector:
    app: ragagent
    component: llm-rag
