apiVersion: v1
kind: Service
metadata:
  name: svc-keycloak
  labels:
    app: keycloak
    component: authentication
spec:
  clusterIP: None
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 8443
    targetPort: 8443
  selector:
    app: keycloak
    component: authentication