apiVersion: v1
kind: Service 
metadata:
  name: svc-postgresql
  labels: 
    app: db-postgresql
    component: postgresql
spec:
  selector:
    app: db-postgresql
    component: postgresql
#    tier: database
  ports:  
  - name: postgresql
    port: 5432
    targetPort: postgresql
  clusterIP: None # Headless
  selector:
    app: db-postgresql
    component: postgresql
---
apiVersion: v1
kind: Service 
metadata:
  name: svc-postgresql-nodeport
  labels: 
    app: db-postgresql
    component: postgresql
spec:
  selector:
    app: db-postgresql
    component: postgresql
#    tier: database
  ports:  
  - port: 5432
    name: postgresql
    nodePort: 30002
  type: NodePort
