apiVersion: v1
kind: Service
metadata:
  name: svc-ragagent
  #  annotations:
  #    alb.ingress.kubernetes.io/healthcheck-path: /ragagent/actuator/health
  labels:
    component: llm-rag
    app: ragagent
spec:
  ports:
    - name: http2
      protocol: TCP
      port: 8080
      targetPort: http2
    - name: http3
      protocol: UDP
      port: 443
      targetPort: http3
  clusterIP: None # Headless. type cannot be LoadBalancer
  selector:
    app: ragagent
    component: llm-rag
#    tier: frontend
#  type: LoadBalancer # Exposes web to traffic from outside of the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ragagent-nodeport
  labels:
    component: llm-rag
    app: ragagent
spec:
  ports:
    - name: http2
      protocol: TCP
      port: 8080
      targetPort: http2
      nodePort: 31002
    - name: http3
      protocol: UDP
      port: 4433
      targetPort: http3
      nodePort: 31003
  type: NodePort
  selector:
    app: ragagent
    component: llm-rag
