apiVersion: v1
kind: Service
metadata:
  name: svc-pgadmin
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    #alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    alb.ingress.kubernetes.io/healthcheck-path: /login
    alb.ingress.kubernetes.io/conditions.rule-path1: >
      [{"field":"http-header","httpHeaderConfig":{"httpHeaderName": "X-Scheme", "values":["https"]}}]
  labels:
    app: pgadmin
    component: postgresql
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
    - protocol: TCP
      port: 443
      targetPort: https
      name: https
  clusterIP: None
  selector:
    app: pgadmin
    component: postgresql
