apiVersion: v1
kind: Service 
metadata:
  name: svc-aspnetapistarter
#  annotations:
#    alb.ingress.kubernetes.io/healthcheck-path: /aspnetapistarter/actuator/health
  labels: 
    component: aspnetapistarter
    app: aspnetapistarter
spec:
  ports:  
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
  clusterIP: None # Headless. type cannot be LoadBalancer
  selector:
    app: aspnetapistarter
    component: aspnetapistarter
#    tier: frontend
#  type: LoadBalancer # Exposes web to traffic from outside of the cluster 
---
apiVersion: v1
kind: Service 
metadata:
  name: svc-aspnetapistarter-nodeport
  labels: 
    component: aspnetapistarter
    app: aspnetapistarter
spec:
  ports:  
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
    nodePort: 31004
  type: NodePort
  selector:
    component: aspnetapistarter
    app: aspnetapistarter
#---
#apiVersion: v1
#kind: Service 
#metadata:
#  name: svc-aspnetapistarter-ingress
#  labels: 
#    app: aspnetapistarter
#spec:
#  ports:  
#  - name: https
#    protocol: TCP
#    port: 443
#    targetPort: 443
#  type: NodePort
#  selector:
#    app: aspnetapistarter
