apiVersion: v1
kind: Service
metadata:
  name: svc-nodejsrestapi
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    alb.ingress.kubernetes.io/healthcheck-path: /health/live
  labels:
    app: nodejsrestapi
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
  clusterIP: None # Headless. type cannot be LoadBalancer
  selector:
    app: nodejsrestapi
#    tier: frontend
#  type: LoadBalancer # Exposes web to traffic from outside of the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nodejsrestapi-nodeport
  labels:
    app: nodejsrestapi
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
      nodePort: 31005
  type: NodePort
  selector:
    app: nodejsrestapi
