apiVersion: v1
kind: Service
metadata:
  name: svc-pgadmin
  labels:
    app: pgadmin
    component: postgresql
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31235
    name: pgadmin
  selector:
    app: pgadmin
    component: postgresql
  type: NodePort
