apiVersion: v1
kind: Service
metadata:
  name: svc-postgresql
  labels:
    app: db-postgresql
    component: postgresql
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
    name: postgresql
  selector:
    app: db-postgresql
    component: postgresql
  clusterIP: None # Headless
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: svc-postgresql-nodeport
  labels:
    app: db-postgresql
    component: postgresql
spec:
  selector:
    app: db-postgresql
    component: postgresql
  ports:
  - port: 5432
    name: postgresql
    nodePort: 30002
  type: NodePort
  sessionAffinity: None
