apiVersion: v1
kind: Service
metadata:
  name: svc-aspnetcorewebapi
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    alb.ingress.kubernetes.io/healthcheck-path: /health/live
  labels:
    component: aspnetcorewebapi
    app: aspnetcorewebapi
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
  clusterIP: None # Headless. type cannot be LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
  selector:
    app: aspnetcorewebapi
    component: aspnetcorewebapi
#    tier: frontend
#  type: LoadBalancer # Exposes web to traffic from outside of the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: svc-aspnetcorewebapi-nodeport
  labels:
    component: aspnetcorewebapi
    app: aspnetcorewebapi
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: https
      nodePort: 31000
  type: NodePort
  selector:
    component: aspnetcorewebapi
    app: aspnetcorewebapi
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: svc-aspnetcorewebapi-ingress
#  labels:
#    app: aspnetcorewebapi
#spec:
#  ports:
#  - name: https
#    protocol: TCP
#    port: 443
#    targetPort: 443
#  type: NodePort
#  selector:
#    app: aspnetcorewebapi
