apiVersion: v1
kind: Service
metadata:
  name: svc-pgadmin
  labels:
    app: pgadmin
    component: postgresql
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      #    nodePort: 30001
      name: http
    - protocol: TCP
      port: 443
      targetPort: https
      #    nodePort: 30001
      name: https
  selector:
    app: pgadmin
    component: postgresql
  type: NodePort
