apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2019-03-13T01:37:57Z"
  name: tomcat-server-config
  namespace: default
  resourceVersion: "8433923"
  selfLink: /api/v1/namespaces/default/configmaps/tomcat-server-config
  uid: a0fb7f61-4530-11e9-9b4d-02755ef07650
data:
  server.xml: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Server port=\"8005\" shutdown=\"SHUTDOWN\">\n
    \ <Listener className=\"org.apache.catalina.startup.VersionLoggerListener\" />\n
    \ <Listener className=\"org.apache.catalina.core.AprLifecycleListener\" SSLEngine=\"on\"
    />\n  <Listener className=\"org.apache.catalina.core.JreMemoryLeakPreventionListener\"
    />\n  <Listener className=\"org.apache.catalina.mbeans.GlobalResourcesLifecycleListener\"
    />\n  <Listener className=\"org.apache.catalina.core.ThreadLocalLeakPreventionListener\"
    />\n  <GlobalNamingResources>\n    <Resource name=\"UserDatabase\" auth=\"Container\"\n
    \             type=\"org.apache.catalina.UserDatabase\"\n              description=\"User
    database that can be updated and saved\"\n              factory=\"org.apache.catalina.users.MemoryUserDatabaseFactory\"\n
    \             pathname=\"conf/tomcat-users.xml\" />\n  </GlobalNamingResources>\n
    \ <Service name=\"Catalina\">\n    <Connector port=\"8080\" protocol=\"HTTP/1.1\"
    enableLookups=\"true\" connectionTimeout=\"20000\" redirectPort=\"8443\" secure=\"true\">\n
    \     <UpgradeProtocol className=\"org.apache.coyote.http2.Http2Protocol\"/>\n
    \   </Connector>\n    <Connector port=\"8009\" protocol=\"AJP/1.3\" redirectPort=\"8443\"
    enableLookups=\"true\"/>\n    <Engine name=\"Catalina\" defaultHost=\"localhost\">\n
    \     <Realm className=\"org.apache.catalina.realm.LockOutRealm\">\n        <Realm
    className=\"org.apache.catalina.realm.UserDatabaseRealm\" resourceName=\"UserDatabase\"/>\n
    \     </Realm>\n      <Host name=\"localhost\"  appBase=\"webapps\" unpackWARs=\"true\"
    autoDeploy=\"true\">\n\t<Valve className=\"org.apache.catalina.valves.RemoteIpValve\"
    protocolHeader=\"x-forwarded-proto\" />            \n        <Valve className=\"org.apache.catalina.valves.ExtendedAccessLogValve\"
    directory=\"logs\" prefix=\"localhost_access_log\" suffix=\".txt\" requestAttributesEnabled=\"true\"\n
    \           pattern=\"time c-ip c-dns cs-method cs-uri-stem cs-uri-query sc-status
    bytes time-taken\" />\n      </Host>\n    </Engine>\n  </Service>\n</Server>\n"
