apiVersion: v1
kind: ConfigMap
metadata:
  name: ragagent
data:
  ragagent_config.json: |
    {
        "ENVIRONMENT": "production",
        "DEBUG": true,
        "TESTING": true,
        "LOGLEVEL": "INFO",
        "SECRET_KEY": "RAGAgent",
        "SQLALCHEMY_TRACK_MODIFICATIONS": false,
        "DB_HOST": "svc-postgresql",
        "DB_DATABASE": "Langchain",
        "DB_MAX_CONNECTIONS": 10,
        "EMBEDDING_MODEL": "embeddinggemma",
        "EMBEDDING_DIMENSIONS": 768,
        "VECTORSTORE_TABLE": "ragagent_vectorstore",
        "MODEL_PROVIDER": "ollama",
        "LLM_RAG_MODEL": "gpt-oss:120b-cloud",
        "OLLAMA_CONTEXT_LENGTH": "8192",
        "NEO4J_URI": "neo4j://svc-neo4j:7687",
        "OLLAMA_CLOUD_URI": "https://ollama.com",
        "OLLAMA_LOCAL_URI": "http://svc-ollama:11434"
    }
