apiVersion: v1
kind: ConfigMap
metadata:
  name: ragagent
data:
  ragagent_config.json: |
    {
        "ENVIRONMENT": "production",
        "DEBUG": true,
        "TESTING": true,
        "LOGLEVEL": "INFO",
        "SECRET_KEY": "RAGAgent",
        "JWT_SECRET_KEY": "RAGAgent",
        "SQLALCHEMY_TRACK_MODIFICATIONS": false,
        "DB_HOST": "svc-postgresql",
        "DB_DATABASE": "LangchainCheckpoint",
        "DB_MAX_CONNECTIONS": 10,
        "EMBEDDING_MODEL": "nomic-embed-text",
        "LLM_RAG_MODEL": "gemma3:27b",
        "CHROMA_URI": "http://svc-chroma:8000",
        "NEO4J_URI": "neo4j://svc-neo4j:7687",
        "OLLAMA_URI": "http://svc-ollama:11434"
    }
