apiVersion: v1
kind: ConfigMap
metadata:
  name: ragagent
data:
  ragagent_config.json: |
    {
        "ENVIRONMENT": "development",
        "DEBUG": true,
        "TESTING": true,
        "LOGLEVEL": "INFO",
        "SECRET_KEY": "RAGAgent",
        "JWT_SECRET_KEY": "RAGAgent",
        "SQLALCHEMY_TRACK_MODIFICATIONS": false,
        "DB_HOST": "svc-postgresql",
        "DB_MAX_CONNECTIONS": 10,
        "EMBEDDING_MODEL": "nomic-embed-text",
        "LLM_RAG_MODEL": "llama3.3",
        "CHROMA_URI": "http://svc-chroma",
        "NEO4J_URI": "neo4j://svc-neo4j:7687",
        "OLLAMA_URI": "http://svc-ollama"
    }
