apiVersion: v1
kind: ConfigMap
metadata:
  name: ragagent
data:
  ragagent_config.json: |
    {
        "ENVIRONMENT": "development",
        "DEBUG": true,
        "TESTING": true,
        "SECRET_KEY": "RAGAgent",
        "JWT_SECRET_KEY": "RAGAgent",
        "SQLALCHEMY_TRACK_MODIFICATIONS": false,
        "DB_HOST": "svc-postgresql",
        "DB_MAX_CONNECTIONS": 10,
        "NEO4J_URI": "neo4j://svc-neo4j:7687",
    }
