apiVersion: v1
kind: Service
metadata:
  name: svc-ragagent
  #  annotations:
  #    alb.ingress.kubernetes.io/healthcheck-path: /ragagent/actuator/health
  labels:
    app: ragagent
    component: llm-rag
spec:
  ports:
    - name: https-udp
      protocol: UDP
      port: 443
      targetPort: https-udp
  clusterIP: None # Headless. type cannot be LoadBalancer
  selector:
    app: ragagent
    component: llm-rag
#    tier: frontend
#  type: LoadBalancer # Exposes web to traffic from outside of the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: svc-ragagent-nodeport
  labels:
    app: ragagent
    component: llm-rag
spec:
  ports:
    - name: https-udp
      protocol: UDP
      port: 443
      targetPort: https-udp
      nodePort: 31003
  type: NodePort
  selector:
    app: ragagent
    component: llm-rag
