apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.applicationName }}
  labels:
    component: {{ .Values.componentName }}
    app: {{ .Values.applicationName }}
spec:
  serviceName: {{ .Values.serviceName }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy: 
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
      component: {{ .Values.componentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        component: {{ .Values.componentName }}
      annotations:
        # Re-evaluates on every upgrade; triggers restart if config changes
        checksum/config: {{ include (print $.Template.BasePath "/nodejsrestapi_config.yml") . | sha512sum }}        
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.applicationName }}
        image: "{{ .Values.image.application.repository }}:{{ .Values.image.application.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: POSTGRESQL_HOST
            value: "{{ .Values.postgresql.hostname }}"
          - name: POSTGRESQL_PORT
            value: "{{ .Values.postgresql.port }}"
          - name: POSTGRESQL_DB
            value: "{{ .Values.postgresql.database }}"
          - name: POSTGRESQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ required "PostgreSQL DB username secretName!" .Values.postgresql.secretName }}
                key: {{ required "PostgreSQL DB username secretKey!" .Values.postgresql.user }}
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ required "PostgreSQL DB password secretName!" .Values.postgresql.secretName }}
                key: {{ required "PostgreSQL DB password secretKey!" .Values.postgresql.passwordKey }}
        {{- if .Values.gemini }}
          - name: GEMINI_API_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.gemini.secretName }}
                key: {{ .Values.gemini.apikey }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.service.port }}
          name: {{ .Values.service.portName }}
          protocol: {{ .Values.service.protocol }}
        {{- with .Values.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeMounts.application }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources.application }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - name: {{ .Values.sidecarName }}
        image: "{{ .Values.image.sidecar.repository }}:{{ .Values.image.sidecar.tag }}"
        {{- with .Values.volumeMounts.sidecar }}
        volumeMounts:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources.sidecar }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
