apiVersion: v1
kind: Secret
metadata:
  name: email-credentials
type: Opaque
data:
  appsettings.email.json: ewogICJFbWFpbFNldHRpbmdzIjogewogICAgIlVzZXJOYW1lIjogIm1lQGVtYWlsLmNvbSIsCiAgICAiUGFzc3dvcmQiOiAibXlhY2NvdW50Lmdvb2dsZS5jb20vc2VjdXJpdHkgYXV0by1nZW5lcmF0ZWQgYXBwIHBhc3N3b3JkIiwKICAgICJQb3J0IjogNDY1LAogICAgIlNlcnZlciI6ICJzbXRwLmdtYWlsLmNvbSIsCiAgICAiVExTIjogdHJ1ZQogIH0KfQo=
