apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth
spec:
  serviceName: svc-geth
  replicas: 1
  selector:
    matchLabels:
      app: geth
      component: execution
  template:
    metadata:
      labels:
        app: geth
        component: execution
    spec:
      containers:
        - name: geth
          image: ethereum/client-go:v1.14.12
          imagePullPolicy: IfNotPresent
          args:
            - --holesky
            - --http
            - --http.addr=0.0.0.0
            - --http.vhosts=geth
            - --ws
            - --ws.addr=0.0.0.0
            - --authrpc.addr=0.0.0.0
            - --authrpc.vhosts=0.0.0.0
            - --authrpc.port=8551
            - --authrpc.jwtsecret=/tmp/jwtsecret
            - --datadir=/data
          ports:
            - containerPort: 8545
              name: gethrpc
              protocol: TCP
            - containerPort: 30303
              name: gethdiscovery
              protocol: UDP
          volumeMounts:
            - name: jwtsecret
              mountPath: /tmp/jwtsecret
              subPath: jwtsecret
              readOnly: true
            - name: geth-data
              mountPath: data
          resources:
            limits:
              memory: 16Gi
            requests:
              memory: 10Gi
      volumes:
        - name: jwtsecret
          secret:
            secretName: jwtsecret
            items:
              - key: jwtsecret
                path: jwtsecret
  volumeClaimTemplates:
    - metadata:
        name: geth-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Gi
        #storageClassName: do-block-storage
