apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth-mainnet-full
spec:
  serviceName: svc-geth-mainnet-full
  replicas: 1
  selector:
    matchLabels:
      app: geth-mainnet-full
      component: geth-mainnet-full
  template:
    metadata:
      labels:
        app: geth-mainnet-full
        component: geth-mainnet-full
    spec:
      containers:
        - name: geth-mainnet-full
          image: ethereum/client-go:v1.14.12
          imagePullPolicy: Always
          args:
            - --http
            - --http.addr=0.0.0.0
            - --http.vhosts=geth-mainnet-full
            - --http.api=eth,net,web3,txpool
            - --ws
            - --ws.addr=0.0.0.0
            - --authrpc.jwtsecret=/tmp/jwtsecret
            - --datadir=/data
          ports:
            - containerPort: 8545
              name: gethrpc
              protocol: TCP
            - containerPort: 30303
              name: gethdiscovery
              protocol: UDP
          volumeMounts:
            - name: jwtsecret
              mountPath: /tmp/jwtsecret
              subPath: jwtsecret
              readOnly: true
            - name: data
              mountPath: "/data"
          resources:
            limits:
              memory: 12000Mi
            requests:
              memory: 10000Mi
      volumes:
        - name: jwtsecret
          secret:
            secretName: jwtsecret
            items:
              - key: jwtsecret
                path: jwtsecret
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1000Gi
        #storageClassName: do-block-storage
