apiVersion: v1
kind: ConfigMap
metadata:
  name: beacon-config
data:
  beacon-config.yml: |
    network: holesky
    rest: true
    rest.address: 0.0.0.0
    rest.port: 9001
    rest.namespace: '*'
    dataDir: /data
    listenAddress: 0.0.0.0
    port: 9000
    eth1: true
    execution.urls: http://svc-geth:8551
    jwtSecret: /tmp/jwtsecret
    metrics: true
    metrics.address: 0.0.0.0
    metrics.port: 9002
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: validator-config
data:
  validator-config.yml: |
    network: holesky
    dataDir: /data
    importKeystores: /tmp/keystores_rw
    importKeystoresPassword: /tmp/password.txt
    server: http://svc-lodestar-beacon:9001
    metrics: true
    metrics.address: 0.0.0.0
    metrics.port: 9002
