apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lodestar-validator
spec:
  serviceName: svc-lodestar-validator
  replicas: 1
  selector:
    matchLabels:
      app: lodestar-validator
      component: lodestar
  template:
    metadata:
      labels:
        app: lodestar-validator
        component: lodestar
    spec:
      initContainers:
        - name: copy-keystores
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              chmod 777 /tmp/keystores_rw
              cp -LH /tmp/keystores/* /tmp/keystores_rw
              ls -alRH /tmp
          volumeMounts:
            - name: validator-keystore
              mountPath: /tmp/keystores
              readOnly: false
            - name: workspace
              mountPath: /tmp/keystores_rw
              readOnly: false
      containers:
        - name: lodestar
          image: chainsafe/lodestar:v1.25.0
          imagePullPolicy: IfNotPresent
          command:
            - ./lodestar
            - validator
            - --rcConfig
            - /tmp/validator-config.yml
          lifecycle:
            postStart:
              exec:
                command:
                  - ls
                  - -alRH
                  - /tmp
          ports:
            - name: metrics
              containerPort: 9002
              protocol: TCP
          volumeMounts:
            - name: validator
              mountPath: /tmp/password.txt
              subPath: password.txt
              readOnly: true
            - name: validator-config
              mountPath: /tmp/validator-config.yml
              subPath: validator-config.yml
              readOnly: true
            - name: validator-keystore
              mountPath: /tmp/keystores
              readOnly: false
            - name: jwtsecret
              mountPath: /tmp/jwtsecret
              subPath: jwtsecret
              readOnly: true
            - name: lodestar-data
              mountPath: data
            - name: workspace
              mountPath: /tmp/keystores_rw
              readOnly: false
          resources:
            limits:
              memory: 16Gi
            requests:
              memory: 10Gi
      volumes:
        - name: jwtsecret
          secret:
            secretName: jwtsecret
            items:
              - key: jwtsecret
                path: jwtsecret
        - name: validator
          secret:
            secretName: validator
            items:
              - key: password.txt
                path: password.txt
        - name: validator-config
          configMap:
            name: validator-config
        - name: validator-keystore
          configMap:
            name: validator-keystore
            defaultMode: 0755
        - name: workspace
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: lodestar-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1000Gi
        #storageClassName: do-block-storage
