apiVersion: v1
kind: Service
metadata:
  name: svc-geth
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    #alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    #alb.ingress.kubernetes.io/healthcheck-path: /health/live
  labels:
    component: execution
    app: geth
spec:
  ports:
    - name: gethrpc
      port: 8545
      protocol: TCP
      targetPort: gethrpc
    - name: p2p-udp
      port: 30303
      protocol: UDP
      targetPort: p2p-udp
    - name: p2p-tcp
      port: 30303
      protocol: TCP
      targetPort: p2p-tcp
    - name: gethauth
      port: 8551
      protocol: TCP
      targetPort: gethauth
    - name: metrics
      protocol: TCP
      port: 6060
      targetPort: metrics
  clusterIP: None # Headless. type cannot be LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
  selector:
    app: geth
    component: execution
#    tier: frontend
#  type: LoadBalancer # Exposes web to traffic from outside of the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: svc-geth-nodeport
  labels:
    component: execution
    app: geth
spec:
  ports:
    - name: gethrpc
      protocol: TCP
      port: 8545
      targetPort: gethrpc
      nodePort: 31005
    - name: gethdiscovery
      protocol: UDP
      port: 30303
      targetPort: gethdiscovery
      nodePort: 31006
  type: NodePort
  selector:
    component: execution
    app: geth
