apiVersion: v1
kind: Service
metadata:
  name: svc-lodestar-beacon
  annotations:
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    #alb.ingress.kubernetes.io/backend-protocol-version: HTTP2
    #alb.ingress.kubernetes.io/healthcheck-path: /health/live
  labels:
    component: lodestar
    app: lodestar-beacon
spec:
  ports:
    - name: lodestar-tcp
      protocol: TCP
      port: 9000
      targetPort: lodestar-tcp
    - name: lodestar-udp
      protocol: UDP
      port: 9000
      targetPort: lodestar-udp
    - name: lodestar-http
      protocol: TCP
      port: 9001
      targetPort: lodestar-http
    - name: metrics
      protocol: TCP
      port: 9002
      targetPort: metrics
  clusterIP: None # Headless. type cannot be LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 60
  selector:
    app: lodestar-beacon
    component: lodestar
#    tier: frontend
#  type: LoadBalancer # Exposes web to traffic from outside of the cluster
---
apiVersion: v1
kind: Service
metadata:
  name: svc-lodestar-nodeport
  labels:
    component: lodestar
    app: lodestar-beacon
spec:
  ports:
    - name: lodestar-tcp
      protocol: TCP
      port: 9000
      targetPort: lodestar-tcp
      nodePort: 31007
    - name: lodestar-udp
      protocol: UDP
      port: 9000
      targetPort: lodestar-udp
      nodePort: 31008
  type: NodePort
  selector:
    component: lodestar
    app: lodestar-beacon
