apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: guest-secret
data:
  username: Z3Vlc3Q=
  password: UEAkJHcwcmQ=
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: guest
spec:
  tags:
  - monitoring
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: guest-secret # name of the secret    
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: admin-secret
data:
  username: YWRtaW4=
  password: UEAkJHcwcmQ=
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: admin
spec:
  tags:
  - monitoring
  - policymaker
  - administrator
  - management
  rabbitmqClusterReference:
    name: rabbitmq
  importCredentialsSecret:
    name: admin-secret # name of the secret
