apiVersion: batch/v1
kind: Job
metadata:
  name: rabbitmq-publisher-job
  labels:
    app: rabbitmq-publisher
    component: rabbitmq
spec:
  #  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: rabbitmq-publisher-job
          image: khteh/rabbitmq-publisher:latest
          imagePullPolicy: Always
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production
            - name: EXCHANGE
              value: "topic_exchange"
            - name: ROUTINGKEY
              value: "kern.info"
            - name: MESSAGE
              value: "Hello World!!!"
          volumeMounts:
            - name: appsettings-production
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
              readOnly: true
            - name: rabbitmq-secret
              mountPath: /app/appsettings.secret.json
              subPath: appsettings.secret.json
              readOnly: true
      volumes:
        - name: appsettings-production
          configMap:
            name: appsettings-production
        - name: rabbitmq-secret
          secret:
            secretName: rabbitmq-secret
            items:
              - key: rabbitmq_secret.json
                path: appsettings.secret.json
