apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-cert
spec:
  # The name of the Kubernetes Secret that will be created
  secretName: rabbitmq-tls-secret
  issuerRef:
    name: letsencrypt-issuer
    kind: Issuer
  #commonName: rabbitmq.khteh.com
  dnsNames:
    #- rabbitmq.khteh.com
    #- localhost
    - "*.rabbitmq-nodes.default.svc.cluster.local"
    - rabbitmq.default.svc.cluster.local
