apiVersion: v1
kind: Service 
metadata:
  name: svc-kern-subscriber
  labels: 
    component: rabbitmq-subscriber
    app: kern-subscriber
spec:
  ports:  
  - name: http
    protocol: TCP
    port: 5000
    targetPort: http
  - name: https
    protocol: TCP
    port: 443
    targetPort: https
  clusterIP: None # Headless. type cannot be LoadBalancer
  selector:
    app: kern-subscriber
---
apiVersion: v1
kind: Service 
metadata:
  name: svc-critical-subscriber
  labels: 
    component: rabbitmq-subscriber
    app: critical-subscriber
spec:
  ports:  
  - name: http
    protocol: TCP
    port: 5000
    targetPort: 5000
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  clusterIP: None # Headless. type cannot be LoadBalancer
  selector:
    app: critical-subscriber
