apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<AWS Account>:role/eksctl-<clustername>-nodegroup-ng-<role of this nodegroup from IAM Roles>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::<AWS Account>:role/eksctl-<clustername>-nodegroup-ng-<role of this nodegroup from IAM Roles>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::<AWS Account>:role/eksctl-<clustername>-nodegroup-ng-<role of this nodegroup from IAM Roles>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::<AWS Account>:role/eksctl-<clustername>-cluster-ServiceRole-<cluster service role from IAM Roles>
      groups:
        - admin
  mapUsers: |
    - userarn: arn:aws:iam::<AWS Account>:user/mickeymouse
      username: mickeymouse
      groups:
        - admin
