apiVersion: v1
kind: Service
metadata:
  name: svc-mysql
  labels:
    app: db-mysql
    component: mysql
spec:
  selector:
    app: db-mysql
    component: mysql
  #    tier: database
  ports:
    - port: 3306
      name: mysql
  clusterIP: None # Headless
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mysql-nodeport
  labels:
    app: db-mysql
    component: mysql
spec:
  selector:
    app: db-mysql
    component: mysql
  #    tier: database
  ports:
    - port: 3306
      name: mysql
      nodePort: 30006
  type: NodePort
