apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ollama
  labels:
    app: ollama
    component: ai-ml-llm
spec:
  serviceName: svc-ollama
  podManagementPolicy: Parallel # Default is OrderedReady
  replicas: 1 #  1 Insufficient memory, 1 Insufficient nvidia.com/gpu if set to more than 1
  selector:
    matchLabels:
      app: ollama # Has to match .spec.template.metadata.labels
      component: ai-ml-llm
  template:
    metadata:
      labels:
        app: ollama # Has to match .spec.selector.matchLabels
        component: ai-ml-llm
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: ollama
          image: khteh/ollama:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: ollama-config
          ports:
            - name: ollama
              containerPort: 11434
              protocol: TCP
          startupProbe: # failureThreshold * periodSeconds long enough to cover the worst case startup time
            httpGet:
              path: /api/version
              port: ollama
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /api/version
              port: ollama
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /api/version
              port: ollama
              scheme: HTTP
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: ollama-persistent-storage
              mountPath: /models
              readOnly: false
            - name: log
              mountPath: /var/log/ollama
          resources:
            requests:
              memory: 45Gi
              nvidia.com/gpu: 1 # Use kubectl describe node <node_name> to check nvidia.com/gpu in Capacity and Allocatable section of the output
            limits:
              nvidia.com/gpu: 1 # Required value: Limit must be set for non overcommitable resources
        - name: fluentd
          image: khteh/fluentd:latest
          volumeMounts:
            - name: fluentd-config
              mountPath: /etc/td-agent
            - name: elasticsearch-template
              mountPath: /tmp/elasticsearch_template.json
              subPath: elasticsearch_template.json
              readOnly: true
            - name: log
              mountPath: /var/log/ollama
            #- mountPath: /fluentd/elastic/tls.crt
            #  name: elasticsearch-ca
            #  subPath: tls.crt
            #  readOnly: true
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
      volumes:
        - name: ollama-config
          configMap:
            name: ollama-config
        - name: fluentd-config
          configMap:
            name: ollama-fluentd-config
        - name: elasticsearch-template
          configMap:
            name: elasticsearch-template
        - name: log
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: ollama-persistent-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
