apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.applicationName }}
  labels:
    component: {{ .Values.componentName }}
    app: {{ .Values.applicationName }}
spec:
  serviceName: {{ .Values.serviceName }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy: 
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
      component: {{ .Values.componentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        component: {{ .Values.componentName }}
      annotations:
        # Re-evaluates on every upgrade; triggers restart if config changes
        checksum/config: {{ include (print $.Template.BasePath "/neo4j_config.yml") . | sha512sum }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.applicationName }}       
          image: "{{ .Values.image.application.repository }}:{{ .Values.image.application.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.secretName }}
                  key: {{ .Values.secrets.secretKey }}
            - name: NEO4J_CONF
              value: {{ .Values.configuration.path }}
            - name: EXTENDED_CONF
              value: {{ .Values.configuration.extended | quote }}
          ports:
            - name: https
              containerPort: {{ .Values.ports.https }}
            - name: http
              containerPort: {{ .Values.ports.http }}
            - name: bolt
              containerPort: {{ .Values.ports.bolt }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- with .Values.volumeClaimTemplates }}
  volumeClaimTemplates:
    {{- toYaml . | nindent 8 }}
  {{- end }}