apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  labels:
    component: {{ .Values.componentName }}
    app: {{ .Values.applicationName }}
spec:
  selector:
    app: {{ .Values.applicationName }}
    component: {{ .Values.componentName }}
  ipFamilyPolicy: {{ .Values.ipFamilyPolicy }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceNameNodePort }}
  labels:
    component: {{ .Values.componentName }}
    app: {{ .Values.applicationName }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.applicationName }}
    component: {{ .Values.componentName }}
  ipFamilyPolicy: {{ .Values.ipFamilyPolicy }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.portName }}
      nodePort: {{ .Values.service.nodePort }}
