apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
  annotations: {{ .Values.service.annotations | toYaml | nindent 4 }}
  labels:
    component: {{ .Values.componentName }}
    app: {{ .Values.applicationName }}
spec:
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.httpsPortName }}
  clusterIP: None
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Values.applicationName }}
    component: {{ .Values.componentName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceNameNodePort }}
  labels:
    component: {{ .Values.componentName }}
    app: {{ .Values.applicationName }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.httpsPort }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
      name: {{ .Values.service.httpsPortName }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Values.applicationName }}
    component: {{ .Values.componentName }}
