apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.applicationName }}
  labels:
    component: {{ .Values.componentName }}
    app: {{ .Values.applicationName }}
spec:
  serviceName: {{ .Values.serviceName }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  replicas: {{ .Values.replicaCount }}
  updateStrategy: 
    type: {{ .Values.updateStrategy }}
  selector:
    matchLabels:
      app: {{ .Values.applicationName }}
      component: {{ .Values.componentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.applicationName }}
        component: {{ .Values.componentName }}
      annotations:
        # Re-evaluates on every upgrade; triggers restart if config changes
        checksum/config: {{ include (print $.Template.BasePath "/appsettings.yml") . | sha512sum }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.applicationName }}
        image: "{{ .Values.image.application.repository }}:{{ .Values.image.application.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "{{ .Values.environment }}"
          - name: ASPNETCORE_URLS
            value: "{{ .Values.urls }}"
          - name: ASPNETCORE_HTTPS_PORT
            value: "{{ .Values.httpsPort }}"
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "{{ .Values.forwardedHeadersEnabled }}"
          - name: DOTNET_TieredPGO
            value: "{{ .Values.tieredPGO }}"
          - name: DOTNET_TC_QuickJitForLoops
            value: "{{ .Values.TC_QuickJitForLoops }}"
          - name: DOTNET_ReadyToRun
            value: "{{ .Values.ReadyToRun }}"
          - name: COMPlus_ThreadPool_ForceMinWorkerThreads
            value: "{{ .Values.ThreadPool_ForceMinWorkerThreads }}"
          - name: COMPlus_ThreadPool_ForceMaxWorkerThreads
            value: "{{ .Values.ThreadPool_ForceMaxWorkerThreads }}"
          - name: PATH_BASE
            value: "{{ .Values.pathBase }}"
        ports:
        - containerPort: {{ .Values.service.httpPort }}
          name: {{ .Values.service.portName }}
          protocol: {{ .Values.service.protocol }}
        - containerPort: {{ .Values.service.httpsPort }}
          name: {{ .Values.service.httpsPortName }}
          protocol: {{ .Values.service.protocol }}
        {{- with .Values.startupProbe }}
        startupProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources.application }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        # https://stackoverflow.com/questions/79981995/helm-reference-values-in-values-yml
        volumeMounts:
          - name: email-credentials
            mountPath: /app/appsettings.email.json
            subPath: appsettings.email.json
            readOnly: true
          - name: appsettings-{{ .Values.applicationName }}-{{ .Values.environment | lower }}
            mountPath: /app/appsettings.{{ .Values.environment }}.json
            subPath: appsettings.{{ .Values.environment }}.json
            readOnly: true
          - name: postgresql-connection
            mountPath: /app/appsettings.postgresql.json
            subPath: appsettings.postgresql.json
            readOnly: true
          - name: log
            mountPath: /var/log/aspnetcore
        terminationMessagePath: {{ .Values.terminationMessagePath }}
        terminationMessagePolicy: {{ .Values.terminationMessagePolicy }}
      - name: {{ .Values.sidecarName }}
        image: "{{ .Values.image.sidecar.repository }}:{{ .Values.image.sidecar.tag }}"
        volumeMounts:
          - name: log
            mountPath: /var/log/aspnetcore
          - name: fluentd-config
            mountPath: /fluentd/etc
          - name: elasticsearch-template
            mountPath: /tmp/elasticsearch_template.json
            subPath: elasticsearch_template.json
            readOnly: true
        {{- with .Values.resources.sidecar }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
        - name: email-credentials
          secret:
            secretName: email-credentials
            items:
              - key: appsettings.email.json
                path: appsettings.email.json
        - name: appsettings-{{ .Values.applicationName }}-{{ .Values.environment | lower }}
          configMap:
            name: appsettings-{{ .Values.applicationName }}-{{ .Values.environment | lower }}
        - name: postgresql-connection
          secret:
            secretName: aspnetcorewebapi
            items:
              - key: aspnetcorewebapi.postgresql.json
                path: appsettings.postgresql.json
        - name: fluentd-config
          configMap:
            name: aspnetcore-fluentd-config
        - name: elasticsearch-template
          configMap:
            name: elasticsearch-template
        - name: log
          emptyDir: {}
