apiVersion: batch/v1
kind: Job
metadata:
  name: redis-cluster-init
  labels:
    app: redis-cluster
    component: redis
spec:
#  ttlSecondsAfterFinished: 100
  backoffLimit: 3
  activeDeadlineSeconds: 100
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: redis-cluster-init-job
        image: khteh/redis-cluster-init:latest
