apiVersion: v1
kind: Service
metadata:
  name: svc-redis-cluster
  labels:
    app: svc-redis-cluster
    component: redis
spec:
  ports:
  - port: 6379
    targetPort: client
    name: client
  - port: 16379
    targetPort: gossip
    name: gossip
  clusterIP: None
  selector:
    app: redis-cluster
    component: redis
